### ISSUE TITLE
To know and Share - PWA, Unit Testing, Composition API, SSR, Typescript, more.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/cms#71]
- [x] Vite - Jaeho. Vite does not support IE11. So, it's not an optoin.
- [x] [Typescript](https://v3.vuejs.org/guide/typescript-support.html#official-declaration-in-npm-packages) - JaeHo
- [ ] PWA - Learn it later because Vue3 is new and there is less information about it.
- [ ] Unit Testing -  Learn it later because Vue3 is new and there is less information about it.
- [ ] [Mixins](https://v3.vuejs.org/guide/mixins.html#basics) - Do it later.
- [ ] [Composition API](https://v3.vuejs.org/guide/composition-api-introduction.html#why-composition-api) - Ace.
- [ ] [SSR](https://v3.vuejs.org/guide/ssr.html) - Do it later since Vue3 is new. Nuxt.js Quasa.js does not support Vue 3 yet.
- [ ] [Routing](https://v3.vuejs.org/guide/routing.html#official-router) - Charles.
- [ ] [State Management](https://v3.vuejs.org/guide/state-management.html#simple-state-management-from-scratch), Options 1. [Vuex](https://blog.logrocket.com/whats-new-in-vuex-4/) - Charles.

**Comment by 0x110a5f** [comment]
Other reference:
[Composition API](https://composition-api.vuejs.org/api.html#ref)
[Composition API Summarized](https://composition-api.vuejs.org/#summary)
[Cheat Sheet](https://www.vuemastery.com/pdf/Vue-3-Cheat-Sheet.pdf)
